/**
 * Cursor adapter (M6-4) — the IDE-agent wake-up.
 *
 * `agent:cursor` on an issue -> run the Cursor CLI in restricted-autonomy mode
 * (files only — no branches, commits, or PRs), then deterministic CI steps handle
 * git, push, and the PR. Runs on a self-hosted runner with Cursor CLI installed
 * (set `DISPATCH_RUNNER=self-hosted`). The PR it opens is NOT auto-merged — the
 * Referee oracle (build + test) gates it.
 *
 * Env:
 *   CURSOR_API_KEY  required; dry-run when absent
 */
import { execFileSync } from "node:child_process";
import type { FighterAdapter, WakeContext, WakeResult } from "./adapter.js";

/** Hard-exclusion guardrail — the adapter never touches these scopes. */
export const CURSOR_EXCLUDED_TERMS = /(auth|payment|secret|migration|delete|DROP|spend)/i;

/** Pure: assemble the Cursor prompt — brief + file-only restriction + exclusion guardrail. */
export function buildCursorPrompt(ctx: WakeContext): string {
  return `${ctx.brief}

---
IMPORTANT: Do NOT create branches, commit, push, or open pull requests.
Only modify or create source files inside the repository — a subsequent CI step handles all Git operations.
Repository: ${ctx.repo}. You are working on branch \`${ctx.branch}\`.
Do NOT touch auth, payments, secrets, database migrations, deletions, or spend limits.
If the brief requires any of these, stop immediately and comment on issue #${ctx.issueNumber} instead of proceeding.`;
}

export const cursorAdapter: FighterAdapter = {
  name: "cursor",
  async wake(ctx: WakeContext): Promise<WakeResult> {
    // Step 1 — exclusion check (before touching anything).
    if (CURSOR_EXCLUDED_TERMS.test(ctx.brief)) {
      return {
        status: "skipped",
        detail: `brief contains excluded scope — not dispatching to Cursor for issue #${ctx.issueNumber}`,
      };
    }

    // Step 2 — dry-run check.
    const apiKey = process.env.CURSOR_API_KEY;
    if (!apiKey) {
      const prompt = buildCursorPrompt(ctx);
      return {
        status: "dry-run",
        detail: `No CURSOR_API_KEY in env — would run Cursor agent for #${ctx.issueNumber}. Prompt preview: ${prompt.slice(0, 200)}…`,
      };
    }

    // Step 3 — run Cursor agent (CLI is pre-installed by the workflow step).
    const prompt = buildCursorPrompt(ctx);
    execFileSync("cursor", ["-p", prompt, "--output-format", "text"], {
      stdio: ["ignore", "inherit", "inherit"],
      env: { ...process.env, CURSOR_API_KEY: apiKey },
    });

    // Step 4 — git: create branch.
    try {
      execFileSync("git", ["checkout", "-b", ctx.branch], { stdio: "inherit" });
    } catch {
      execFileSync("git", ["checkout", ctx.branch], { stdio: "inherit" });
    }

    // Step 5 — git: commit and push.
    execFileSync("git", ["add", "-A"], { stdio: "inherit" });
    execFileSync(
      "git",
      ["commit", "-m", `feat(#${ctx.issueNumber}): implement issue #${ctx.issueNumber}\n\n[cursor agent]`],
      { stdio: "inherit" }
    );
    execFileSync("git", ["push", "--set-upstream", "origin", ctx.branch], { stdio: "inherit" });

    // Step 6 — open PR.
    const prUrl = execFileSync(
      "gh",
      ["pr", "create", "--title", `feat(#${ctx.issueNumber}): implement issue #${ctx.issueNumber}`, "--body", `Closes #${ctx.issueNumber}\n\nGenerated by Cursor agent.`],
      { encoding: "utf8" }
    ).trim();

    // Step 7 — done-signal comment on the PR.
    const prMatch = /\/pull\/(\d+)/.exec(prUrl);
    if (prMatch) {
      execFileSync(
        "gh",
        ["pr", "comment", prMatch[1], "--body", `@hayssamhob ✅ #${ctx.issueNumber} done — Cursor agent completed the implementation.`],
        { stdio: "inherit" }
      );
    }
    return { status: "woken", detail: `PR opened: ${prUrl}` };
  },
};
