/**
 * The Evolution loop (M5-5) — re-expresses `ring/learnings.py` against recipe gotchas.
 *
 * When a detector (CircleDetector, StallDetector) fires repeatedly, the evolution
 * loop auto-appends a gotcha to `gotchas.md` so the next Fighter run avoids the
 * same failure pattern. This is the "the model forgets, the repo doesn't" memory
 * layer made actionable.
 *
 * Flow:
 *   detector fires → recordSignal() → threshold reached → appendGotcha()
 *   → gotchas.md updated → next dispatch reads gotchas.md → avoids the pattern
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";

export interface DetectorSignal {
  type: "circle" | "stall";
  subtype: string; // e.g. "same_region", "same_error", "net_zero", "no_diff", "identical_diff"
  round: number;
  reason: string;
}

export interface GotchaEntry {
  id: string; // e.g. "G6"
  title: string;
  symptom: string;
  firstSeen: string; // issue/PR reference
  rule: string[];
}

/**
 * Tracks detector signals and appends a gotcha when a pattern repeats enough.
 * The threshold prevents noise — a single stall is not a gotcha, but 3 stalls
 * with the same signature across runs means there's a systematic issue worth
 * recording.
 */
export class EvolutionLoop {
  private signalCounts = new Map<string, DetectorSignal[]>();
  private gotchasPath: string;
  private appendThreshold: number;

  constructor(opts: { gotchasPath?: string; appendThreshold?: number } = {}) {
    this.gotchasPath = opts.gotchasPath ?? "gotchas.md";
    this.appendThreshold = opts.appendThreshold ?? 3;
  }

  /**
   * Record a detector signal. If the same (type, subtype) pattern reaches
   * the threshold, a gotcha is appended to gotchas.md.
   *
   * Returns the appended GotchaEntry if one was written, null otherwise.
   */
  recordSignal(signal: DetectorSignal): GotchaEntry | null {
    const key = `${signal.type}:${signal.subtype}`;
    const signals = this.signalCounts.get(key) ?? [];
    signals.push(signal);
    this.signalCounts.set(key, signals);

    if (signals.length >= this.appendThreshold) {
      const gotcha = this.buildGotcha(key, signals);
      this.appendGotcha(gotcha);
      // Reset the counter after appending — the gotcha is now in the file
      this.signalCounts.set(key, []);
      return gotcha;
    }
    return null;
  }

  private buildGotcha(key: string, signals: DetectorSignal[]): GotchaEntry {
    const nextId = this.nextGotchaId();
    const signal = signals[0];
    const count = signals.length;

    const titleMap: Record<string, string> = {
      "circle:same_region": "Fighter re-edits the same code region across rounds",
      "circle:same_error": "Fighter reintroduces the same error after a fix",
      "circle:net_zero": "Fighter adds and removes the same lines (net-zero progress)",
      "stall:no_diff": "Fighter produces no diff across multiple rounds",
      "stall:identical_diff": "Fighter repeats an identical diff across rounds",
    };

    const title = titleMap[key] ?? `Repeated ${signal.type} pattern: ${signal.subtype}`;
    const symptom = `Detector "${signal.type}/${signal.subtype}" fired ${count} times. Last reason: ${signal.reason}`;
    const firstSeen = `Evolution loop — auto-appended after ${count} ${signal.type} signals`;

    const rule: string[] = [
      `When the ${signal.type} detector fires with subtype "${signal.subtype}", the Fighter is stuck in a loop.`,
      `Interrupt the loop early — do not let the Fighter retry the same approach.`,
      `If the task is mechanical, route to a cheaper tier (ollama) or escalate to the Coach.`,
      `This gotcha was auto-generated by the Evolution loop (M5-5) after ${count} repeated signals.`,
    ];

    return { id: nextId, title, symptom, firstSeen, rule };
  }

  private nextGotchaId(): string {
    const existing = this.readExistingGotchas();
    const ids = existing
      .map((g) => g.match(/^## (G\d+)/))
      .filter(Boolean)
      .map((m) => m![1]);
    if (ids.length === 0) return "G6"; // G1-G5 already exist
    const maxNum = Math.max(...ids.map((id) => parseInt(id.slice(1), 10)));
    return `G${maxNum + 1}`;
  }

  private readExistingGotchas(): string[] {
    if (!existsSync(this.gotchasPath)) return [];
    const content = readFileSync(this.gotchasPath, "utf8");
    return content.split("\n").filter((l) => l.startsWith("## G"));
  }

  private appendGotcha(gotcha: GotchaEntry): void {
    const section = this.formatGotchaSection(gotcha);
    if (existsSync(this.gotchasPath)) {
      const content = readFileSync(this.gotchasPath, "utf8");
      writeFileSync(this.gotchasPath, content.trimEnd() + "\n\n" + section + "\n", "utf8");
    } else {
      writeFileSync(this.gotchasPath, section + "\n", "utf8");
    }
  }

  private formatGotchaSection(g: GotchaEntry): string {
    const ruleLines = g.rule.map((r) => r).join("\n");
    return `## ${g.id} — ${g.title}

**Symptom.** ${g.symptom}

**First seen.** ${g.firstSeen}

**Rule.**
${ruleLines}`;
  }

  /** Reset all signal counts — useful for testing. */
  reset(): void {
    this.signalCounts.clear();
  }

  /** Get current signal count for a key — useful for testing. */
  signalCount(key: string): number {
    return this.signalCounts.get(key)?.length ?? 0;
  }
}
